import { ownerEmail } from '@/lib/ownerNotify'
import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { upsertContact } from '@/lib/contacts'
import { getSupabase } from '@/lib/supabase'
import { escapeHtml } from '@/lib/escapeHtml'
import { mailToHref } from '@/lib/emailSafety'
import { screenCmCheerTotals, VALID_PAYMENT_METHODS } from '@/lib/cmCheerOrder'
import { resolveFundraiserTeam } from '@/lib/fundraiserTeams'
import { guardRate, intakeRule } from '@/lib/rateLimit'

export const dynamic = 'force-dynamic'

interface OrderItem {
  name: string
  qty: number
  unit_price: number
  line_total: number
  cost_per_unit: number
}

export async function POST(req: NextRequest) {
  const limited = guardRate(req, intakeRule('cm-cheer-order'))
  if (limited) return limited

  const body = await req.json()
  const {
    athleteName,
    parentName,
    email,
    phone,
    paymentMethod,
    total,
    totalCost,
    totalProfit,
    itemsData,
    items: itemsString,
    team: postedTeam,
  } = body

  if (!athleteName || !parentName || !email || !phone || !paymentMethod) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }
  if (!itemsData || !Array.isArray(itemsData) || itemsData.length === 0) {
    return NextResponse.json({ error: 'No items in order' }, { status: 400 })
  }
  if (itemsData.length > 40) {
    return NextResponse.json({ error: 'Too many items in one order' }, { status: 400 })
  }
  if (!VALID_PAYMENT_METHODS.includes(String(paymentMethod))) {
    return NextResponse.json({ error: 'Invalid payment method' }, { status: 400 })
  }

  /**
   * Which fundraiser this is. An ABSENT value is `cm-cheer` — `/cm-cheer` and
   * `/li-high` predate the field and do not send it — but an unknown value is
   * refused rather than defaulted, because silently filing a Sharks order under
   * CM Cheer is exactly the mix-up the `team` column was added to stop.
   */
  const team = resolveFundraiserTeam(postedTeam)
  if (!team) {
    return NextResponse.json({ error: 'Unknown fundraiser' }, { status: 400 })
  }

  /**
   * THE TOTAL, THE COST AND THE PROFIT ALL ARRIVE FROM THE BROWSER.
   *
   * `total`, `totalCost` and `totalProfit` were written to `subtotal_cents`,
   * `cost_cents` and `profit_cents` exactly as posted, and `itemsData` carries a
   * `unit_price` and a `cost_per_unit` per line. The prices live in
   * `data-price` / `data-cost` attributes in TWO page components
   * (`/cm-cheer` and `/li-high`) and nowhere on the server — so there is no
   * catalogue to re-derive from, and the table already holds 21 real orders
   * priced this way.
   *
   * Re-pricing would mean porting two live order forms' markup into a server
   * catalogue, which is a change to somebody else's storefront, so it is recorded
   * as needs-Adam instead. What is done here is the part that is unambiguously
   * ours: the numbers are bounded and CROSS-CHECKED against the line items, and a
   * disagreement is written where a human looks (`status_note`) rather than
   * accepted in silence. Rule 14 — a mismatch nobody records is invisible, and an
   * invisible bookkeeping error is a loss.
   */
  const money = screenCmCheerTotals(total, totalCost, totalProfit, itemsData)
  if (!money.ok) {
    console.warn(`cm-cheer-order: refused totals from ${email} — ${money.reason}`)
    return NextResponse.json({ error: `We could not accept that order: ${money.reason}` }, { status: 400 })
  }
  if (money.note) {
    console.warn(`cm-cheer-order: total mismatch from ${email} — ${money.note}`)
  }

  const supabase = getSupabase()

  // Insert order — order_ref generated by DB trigger
  const { data: order, error } = await supabase
    .from('cm_cheer_orders')
    .insert({
      order_ref: '',   // trigger overwrites this, and reads `team` to pick the prefix
      team: team.slug,
      athlete_name: athleteName,
      parent_name: parentName,
      email,
      phone,
      payment_method: paymentMethod,
      items: itemsData,
      subtotal_cents: money.subtotalCents,
      cost_cents: money.costCents,
      profit_cents: money.profitCents,
      status: 'pending_payment',
      status_note: money.note,
    })
    .select('id, order_ref')
    .single()

  if (error || !order) {
    console.error('DB insert error:', error)
    return NextResponse.json({ error: 'Failed to save order' }, { status: 500 })
  }

  // Upsert contact
  await upsertContact({
    name: parentName,
    email,
    phone: phone || null,
    sourceDetail: `${team.slug}-fundraiser`,
    serviceInterests: ['fundraiser'],
    marketingConsent: false,
  }).catch(err => console.error('Contact upsert error (non-fatal):', err))

  // Emails
  if (process.env.RESEND_API_KEY) {
    const resend = new Resend(process.env.RESEND_API_KEY)
    const from = process.env.RESEND_FROM_EMAIL || 'noReply@mail.hosthampton.com'
    const paymentBadge = paymentMethod === 'venmo'
      ? '<span style="background:#008CFF;color:#fff;padding:2px 10px;border-radius:999px;font-size:12px;font-weight:700;">VENMO</span>'
      : '<span style="background:#22c55e;color:#fff;padding:2px 10px;border-radius:999px;font-size:12px;font-weight:700;">CASH TO COACH</span>'

    // The emails quote the STORED total, not the posted one. Asking a customer
    // for a number the order book does not hold is rule 10 with money on it.
    const storedTotal = (money.subtotalCents / 100).toFixed(2)
    const itemRows = (itemsData as OrderItem[])
      .map(i => `<tr><td style="padding:6px 0;color:#555;font-size:14px;">${i.qty}x ${escapeHtml(i.name)}</td><td style="padding:6px 0;text-align:right;font-weight:600;font-size:14px;">${Number(i.line_total).toFixed(2)}</td></tr>`)
      .join('')

    await Promise.allSettled([
      // Admin notification
      resend.emails.send({
        from,
        to: ownerEmail(),
        subject: `📦 ${team.name} Order ${order.order_ref} — ${athleteName}`,
        replyTo: email,
        html: `
<div style="font-family:sans-serif;max-width:560px;margin:0 auto;color:#111;">
  <div style="background:#111;border-top:4px solid ${team.emailAccent};padding:20px 28px;border-radius:10px 10px 0 0;">
    <h1 style="color:#fff;margin:0;font-size:18px;letter-spacing:0.05em;">${escapeHtml(team.name.toUpperCase())} — NEW ORDER</h1>
    <p style="color:#999;margin:4px 0 0;font-size:13px;">${escapeHtml(order.order_ref)} · ${escapeHtml(paymentMethod.toUpperCase())}</p>
  </div>
  <div style="background:#fff;border:1px solid #e5e5e5;border-top:none;padding:24px 28px;border-radius:0 0 10px 10px;">
    <table style="width:100%;border-collapse:collapse;margin-bottom:16px;">
      <tr><td style="color:#888;font-size:13px;padding:4px 0;width:120px;">Athlete</td><td style="font-weight:600;font-size:14px;">${escapeHtml(athleteName)}</td></tr>
      <tr><td style="color:#888;font-size:13px;padding:4px 0;">Parent/Buyer</td><td style="font-weight:600;font-size:14px;">${escapeHtml(parentName)}</td></tr>
      <tr><td style="color:#888;font-size:13px;padding:4px 0;">Email</td><td><a href="${mailToHref(email)}" style="color:#111;font-weight:600;font-size:14px;">${escapeHtml(email)}</a></td></tr>
      <tr><td style="color:#888;font-size:13px;padding:4px 0;">Phone</td><td style="font-weight:600;font-size:14px;">${escapeHtml(phone)}</td></tr>
      <tr><td style="color:#888;font-size:13px;padding:4px 0;">Payment</td><td style="padding:4px 0;">${paymentBadge}</td></tr>
    </table>
    <div style="background:#f9f9f9;border-radius:8px;padding:14px 16px;border:1px solid #eee;">
      <table style="width:100%;">${itemRows}
        <tr><td colspan="2" style="border-top:1px solid #ddd;padding-top:8px;"></td></tr>
        <tr><td style="font-weight:700;font-size:15px;">Total</td><td style="text-align:right;font-weight:800;font-size:18px;color:${team.emailAccent};">$${storedTotal}</td></tr>
      </table>
    </div>
    <p style="margin-top:16px;font-size:12px;color:#aaa;">Order ID: ${escapeHtml(order.order_ref)} · Manage at hosthampton.com${team.ordersPath}</p>
  </div>
</div>`,
      }),

      // Customer confirmation
      resend.emails.send({
        from,
        to: email,
        subject: `Order Confirmed — ${order.order_ref} · ${team.name} Fundraiser`,
        html: `
<div style="font-family:sans-serif;max-width:520px;margin:0 auto;color:#111;">
  <div style="background:#111;border-top:4px solid ${team.emailAccent};padding:24px 28px;text-align:center;border-radius:10px 10px 0 0;">
    <p style="color:#fff;font-size:13px;font-weight:700;letter-spacing:0.2em;text-transform:uppercase;margin:0 0 6px;opacity:0.7;">${escapeHtml(team.organization)}</p>
    <h1 style="color:#fff;margin:0;font-size:26px;font-weight:800;letter-spacing:0.05em;">${escapeHtml(team.name.toUpperCase())} FUNDRAISER</h1>
  </div>
  <div style="background:#fff;border:1px solid #e5e5e5;border-top:none;padding:28px;border-radius:0 0 10px 10px;">
    <h2 style="margin:0 0 4px;font-size:20px;">Thanks, ${escapeHtml(parentName.split(' ')[0])}! 🎉</h2>
    <p style="color:#555;font-size:14px;margin-bottom:20px;">Your order has been received. Your order number is:</p>
    <div style="background:${team.emailAccent};color:#fff;text-align:center;padding:12px;border-radius:8px;font-size:22px;font-weight:800;letter-spacing:0.1em;margin-bottom:20px;">${escapeHtml(order.order_ref)}</div>
    <div style="background:#f9f9f9;border-radius:8px;padding:14px 16px;border:1px solid #eee;margin-bottom:20px;">
      <p style="font-size:12px;font-weight:700;text-transform:uppercase;color:#888;margin:0 0 8px;">Athlete: ${escapeHtml(athleteName)}</p>
      <table style="width:100%;">${itemRows}
        <tr><td colspan="2" style="border-top:1px solid #ddd;padding-top:8px;"></td></tr>
        <tr><td style="font-weight:700;">Total</td><td style="text-align:right;font-weight:800;color:${team.emailAccent};">$${storedTotal}</td></tr>
      </table>
    </div>
    ${paymentMethod === 'venmo' ? `
    <div style="background:#e8f4ff;border-radius:8px;padding:14px;border:1px solid #bde0ff;margin-bottom:16px;">
      <p style="margin:0;font-size:14px;font-weight:700;">💳 Payment Reminder</p>
      <p style="margin:6px 0 0;font-size:13px;color:#555;">Please complete your Venmo payment of <strong>$${storedTotal}</strong> to <strong>${escapeHtml(team.venmoEmailHandle)}</strong> and include <strong>${escapeHtml(athleteName)}</strong> in the memo.</p>
    </div>` : `
    <div style="background:#f0fdf4;border-radius:8px;padding:14px;border:1px solid #bbf7d0;margin-bottom:16px;">
      <p style="margin:0;font-size:14px;font-weight:700;">💵 Payment Reminder</p>
      <p style="margin:6px 0 0;font-size:13px;color:#555;">Please bring <strong>$${storedTotal} cash</strong> to your coach. Reference order <strong>${escapeHtml(order.order_ref)}</strong>.</p>
    </div>`}
    <p style="font-size:12px;color:#aaa;text-align:center;margin-top:16px;">Questions? Contact your coach or reply to this email.</p>
  </div>
</div>`,
      }),
    ])
  }

  return NextResponse.json({ success: true, order_ref: order.order_ref })
}
