-- ════════════════════════════════════════════════════════════════
-- Leads batch 2 (2026-08): Gemini-scraped East End B2B / community orgs
--   Source: hh-scraped-contacts.csv.txt (85 rows; 44 already existed from the
--   prior ai-scrape-2026-08 batch, all is_business=true — SKIPPED, never touched).
--   Inserts the 41 genuinely-new orgs. Cold outreach: status='lead',
--   NO opt-in assumed (email/sms false). Idempotent: ON CONFLICT DO NOTHING.
--   Tags derived in-SQL from business_type + source_detail, scoped to this batch
--   so existing rows are never re-tagged. Reviewed before run.
-- ════════════════════════════════════════════════════════════════

INSERT INTO public.contacts
  (email, phone, status, source, source_detail, is_business, business_name, business_type, city, email_opt_in, sms_opt_in, notes)
VALUES
  ('info@crestwoodcountryday.com', '(631) 692-6361', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Crestwood Country Day School', 'Preschool / Private School', 'Melville', false, false, 'Contact: Admissions / Events Director | Website: crestwoodcountryday.com | Distance/Region: West Suffolk (~35 mi) | Target Service: Auction Donation & Custom Spirit Bags/Hats | Strategy: Full-day preschool through upper grades; pitch class party rentals and custom spirit merch for parent events.'),
  ('info@smithtownchristian.org', '(631) 265-3334', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Smithtown Christian School', 'Preschool / Private School', 'Smithtown', false, false, 'Contact: Admissions / Events | Website: smithtownchristian.org | Distance/Region: Central Suffolk | Target Service: Auction Donation & Custom Spirit Bags/Hats | Strategy: PK-12 Christian school; auction gift certificates and custom embroidered bags for parent welcome kits.'),
  ('info@bloomlearningcenter.com', '(631) 287-2100', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Bloom Learning Center', 'Preschool / Private School', 'Southampton', false, false, 'Contact: Campus Director / Enrollment | Website: bloomlearningcenter.com | Distance/Region: East End / Mid Suffolk | Target Service: Auction Donation & Custom Spirit Bags/Hats | Strategy: Multi-campus early childhood center; class party space + custom branded totes for family events.'),
  ('info@eddiearthursalon.com', '(631) 537-8000', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Eddie Arthur Salon', 'Salon / Mom Partner', 'Bridgehampton', false, false, 'Contact: Salon Manager | Website: eddiearthursalon.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: High-traffic Bridgehampton luxury salon; pitch permanent jewelry pop-up during peak blowout/styling weekends.'),
  ('bookhampton@warrentricomi.com', '(631) 324-3036', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Warren Tricomi Sag Harbor', 'Salon / Mom Partner', 'Sag Harbor', false, false, 'Contact: Front Desk / Bookings | Website: warrentricomi.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Manhattan-glamour salon with strong local base; co-host styling + permanent jewelry VIP nights and custom totes.'),
  ('info@rowemedspa.com', '(631) 500-9090', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Rowe Medspa', 'Salon & MedSpa', 'Water Mill', false, false, 'Contact: Practice Manager | Website: rowemedspa.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: High-end Hamptons medspa; host exclusive Glow & Gold permanent jewelry nights for affluent clientele.'),
  ('info@valeryjoseph.com', '(631) 537-8900', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Valery Joseph Salon', 'Salon / Mom Partner', 'Bridgehampton', false, false, 'Contact: Salon Director | Website: valeryjoseph.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Luxury hair destination; pitch co-branded VIP client nights pairing signature cuts with permanent jewelry fittings.'),
  ('info@revolvehairsalon.com', '(631) 377-3107', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Revolve Hair', 'Salon / Mom Partner', 'Southampton', false, false, 'Contact: Owner / Manager | Website: revolvehairsalon.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Personalized luxury salon; offer permanent jewelry as add-on perk for loyal Hamptons clientele events.'),
  ('info@kevinmaplesalon.com', '(631) 283-8230', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Kevin Maple Salon', 'Salon / Mom Partner', 'Southampton', false, false, 'Contact: Front Desk / Events | Website: kevinmaplesalon.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Intimate setting ideal for private shopping nights featuring permanent jewelry and custom luxury totes.'),
  ('info@coreyandersonsalon.com', '(631) 537-1630', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Corey Anderson Salon', 'Salon / Mom Partner', 'Water Mill', false, false, 'Contact: Salon Manager | Website: coreyandersonsalon.com | Distance/Region: East End (10-mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Precision cuts & extensions specialist; pitch bridal/party pop-ups with permanent jewelry station.'),
  ('info@marottamd.com', '(631) 982-2022', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Marotta MedSpa', 'MedSpa & Wellness', 'Smithtown', false, false, 'Contact: Events Coordinator | Website: marottamd.com | Distance/Region: Central Suffolk (~30 mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Physician-led medspa; host exclusive Botox + permanent jewelry VIP evenings for high-net-worth local moms.'),
  ('info@hellogorgeousli.com', '(631) 848-6758', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Hello Gorgeous Skincare & Esthetics', 'MedSpa & Beauty', 'Babylon', false, false, 'Contact: Manager / Owner | Website: hellogorgeousli.com | Distance/Region: South Shore (~40 mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Results-driven medspa; pitch seasonal Spark & Style permanent jewelry host nights.'),
  ('info@flawlessskinaesthetics.com', '(631) 285-3494', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Flawless Skin Aesthetics', 'MedSpa & Beauty', 'Centereach', false, false, 'Contact: Front Desk / Events | Website: flawlessskinaesthetics.com | Distance/Region: Central Suffolk (~25 mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Holistic skincare focus; cross-promote permanent jewelry pop-ups during promotional treatment parties.'),
  ('jen@jsalta.com', '(631) 974-8010', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'J Salta - Jeweler & Artist', 'Salon / Jewelry Studio', 'Huntington Station', false, false, 'Contact: Jen Salta / Owner-Jeweler | Website: jsalta.com | Distance/Region: West Suffolk (~35 mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Women-owned private jewelry studio already specializing in permanent welded bracelets inside Suite Pieces; propose a co-hosted VIP fitting night paired with Host Hampton party space for cross-promotion.'),
  ('info@browclinicny.com', '(631) 458-7025', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'The Brow Clinic NY', 'Salon & MedSpa', 'Huntington', false, false, 'Contact: Studio Manager | Website: browclinicny.com | Distance/Region: West Suffolk (~35 mi) | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Established Huntington Village permanent jewelry + brow studio drawing clients from across Suffolk; pitch a joint Glow & Gold mother-daughter pop-up night with custom tote favors.'),
  ('info@evolutionmedspali.com', '(631) 499-5700', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; b2b partnership)', true, 'Evolution MedSpa', 'Salon & MedSpa', 'Commack', false, false, 'Contact: Spa Manager | Website: evolutionmedspali.com | Distance/Region: West Suffolk | Target Service: Permanent Jewelry Pop-Up & VIP Night | Strategy: Full-service non-invasive aesthetics center with an active local client base; propose an after-hours VIP client night combining a permanent jewelry bar with custom branded tote gift bags.'),
  ('info@riverheadlittleleague.org', '(631) 727-2111', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Riverhead Little League', 'Sports & Athletics', 'Riverhead', false, false, 'Contact: League Coordinator | Website: riverheadlittleleague.org | Distance/Region: Mid Suffolk / Gate (~16 mi) | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Community staple; end-of-season celebration packages + custom embroidered snapback hats.'),
  ('info@susaacademy.com', '(631) 617-6758', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'SUSA Academy', 'Sports & Athletics', 'Central Islip', false, false, 'Contact: Program Director | Website: susaacademy.com | Distance/Region: Mid Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Large competitive soccer complex; end-of-season party packages + custom team hats and drawstring bags.'),
  ('info@longislandslammers.com', '(631) 835-1322', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Long Island Slammers', 'Sports & Athletics', 'Setauket', false, false, 'Contact: Club Director | Website: longislandslammers.com | Distance/Region: North Shore / Central | Target Service: End-of-Season Party & Custom Team Hats | Strategy: ECNL competitive club; custom high-end team hats and athletic bags for seasonal fundraisers.'),
  ('info@brentwoodyouthsoccer.com', '(631) 273-0210', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Brentwood Youth Soccer Club', 'Sports & Athletics', 'Brentwood', false, false, 'Contact: Board Director | Website: brentwoodyouthsoccer.com | Distance/Region: West Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Long-standing non-profit club; party venue discounts + bulk custom printed foam trucker hats.'),
  ('eddie@susaacademy.com', '(631) 623-6535', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Baymen Soccer Club', 'Youth Sports League', 'West Sayville', false, false, 'Contact: Fabio Berlingieri / Principal Officer | Website: baymensoccer.com | Distance/Region: South Shore | Target Service: End-of-Season Party & Custom Patch Trucker Hats | Strategy: Non-profit volunteer-run youth soccer club (est. 1981) partnered with SUSA Academy; pitch end-of-season party packages plus custom patch trucker hats and drawstring bags for intramural and travel teams.'),
  ('info@gym-nest.com', '(631) 205-5437', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Gym-Nest Gymnastics & Cheer', 'Dance & Cheer Studio', 'Medford', false, false, 'Contact: Studio Director | Website: gym-nest.com | Distance/Region: Mid Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Premier gymnastics/cheer facility; pitch birthday venue packages + custom glitter patch trucker hats and team tote bags.'),
  ('centereach@gmgc.com', '(631) 981-4653', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Gold Medal Gymnastics Centereach', 'Dance & Cheer Studio', 'Centereach', false, false, 'Contact: Location Manager | Website: gmgc.com | Distance/Region: Central Suffolk (~25 mi) | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Large gymnastics center; offer party space rentals + bulk custom embroidered team bags and hats for recitals.'),
  ('info@stagedoordancer.com', '(631) 654-8858', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Stage Door School of Dance', 'Dance & Cheer Studio', 'Patchogue', false, false, 'Contact: Studio Owner | Website: stagedoordancer.com | Distance/Region: South Shore (~22 mi) | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Comprehensive dance facility; host themed birthday parties + supply custom dance duffels and recital merch.'),
  ('info@paramountdanceacademy.com', '(631) 730-8812', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Paramount Dance Academy', 'Dance & Cheer Studio', 'Holtsville', false, false, 'Contact: Studio Director | Website: paramountdanceacademy.com | Distance/Region: Mid Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Competitive and recreational programs; pitch custom team hats/bags for competition season and recital gear.'),
  ('info@dxny.dance', '(631) 462-3969', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'DXNY Dance Xtreme', 'Dance & Cheer Studio', 'Hauppauge', false, false, 'Contact: Studio Owner | Website: dxny.dance | Distance/Region: West/Mid Suffolk (~32 mi) | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Established competitive studio; bulk custom patch hats and personalized totes for competition teams.'),
  ('info@lidanceconnection.com', '(631) 224-7134', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Dance Connection (Islip & Bay Shore)', 'Dance & Cheer Studio', 'Islip', false, false, 'Contact: Front Desk / Events | Website: lidanceconnection.com | Distance/Region: South Shore Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: 35-year multi-location dance school with recital/competition teams; pitch bulk custom patch trucker hats and embroidered duffels for competition season plus birthday party venue cross-promotion.'),
  ('gravitycheer1@aol.com', '(631) 676-2041', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Gravity Cheer', 'Dance & Cheer Studio', 'Holbrook', false, false, 'Contact: Studio Manager | Website: gravitycheer.com | Distance/Region: Mid Suffolk (~25 mi) | Target Service: End-of-Season Party & Custom Team Hats | Strategy: Long Island''s first all-star cheer gym with a large competitive roster; bulk custom glitter patch trucker hats and personalized team tote bags for competition season fundraisers.'),
  ('julies.gym@hotmail.com', '(631) 447-1389', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Julie''s Gym Gymnastics for Kid''s Inc.', 'Dance & Cheer Studio', 'Patchogue', false, false, 'Contact: Miss Julie J. / Owner | Website: juliesgym.com | Distance/Region: South Shore (~22 mi) | Target Service: Birthday Venue & Custom Team Hats | Strategy: Long-running Patchogue gymnastics facility that already hosts private birthday parties; pitch full-service party add-ons and custom embroidered team/recital bags.'),
  ('info@millenniumkarate.com', '(631) 499-0600', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Millennium Martial Arts & Fitness', 'Martial Arts Dojo', 'Smithtown', false, false, 'Contact: Kyoshi Mike / Owner | Website: millenniummartialarts.com | Distance/Region: Central Suffolk | Target Service: End-of-Season Party & Custom Team Hats | Strategy: 30-year Okinawan karate dojo already running in-house birthday parties for Smithtown/Commack families; propose custom patch trucker hats and belt-test gift bags as an add-on upsell.'),
  ('info@centerport-yc.org', '(631) 261-5440', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Centerport Yacht Club', 'Yacht & Country Club', 'Centerport', false, false, 'Contact: General Manager / Events | Website: centerport-yc.org | Distance/Region: North Shore | Target Service: Custom Embroidered Canvas Totes | Strategy: North Shore yacht club with junior sailing; supply high-end custom canvas totes and sun hats.'),
  ('admin@siyc.com', '(631) 749-0888', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Shelter Island Yacht Club', 'Yacht & Country Club', 'Shelter Island Heights', false, false, 'Contact: Junior Program Director | Website: siyc.com | Distance/Region: East End / North Fork | Target Service: Custom Embroidered Canvas Totes | Strategy: Historic club with junior sailing; custom luxury embroidered totes and merch for junior programs and social events.'),
  ('info@breakwateryc.org', '(631) 725-4604', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Breakwater Yacht Club', 'Yacht & Country Club', 'Sag Harbor', false, false, 'Contact: Clubhouse Manager | Website: breakwateryc.org | Distance/Region: East End (10-mi) | Target Service: Custom Embroidered Canvas Totes | Strategy: Sag Harbor yacht club; custom high-density canvas gear totes for junior sailing and social programs.'),
  ('info@liyc.org', '(631) 669-3270', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Long Island Yacht Club', 'Yacht & Country Club', 'Babylon', false, false, 'Contact: Club Manager | Website: liyc.org | Distance/Region: South Shore | Target Service: Custom Embroidered Canvas Totes | Strategy: Yacht & social club on Great South Bay; custom embroidered caps and totes for junior and family events.'),
  ('manager@northportyachtclub.com', '(631) 261-7633', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Northport Yacht Club', 'Yacht & Country Club', 'Northport', false, false, 'Contact: General Manager | Website: northportyachtclub.com | Distance/Region: North Shore | Target Service: Custom Embroidered Canvas Totes | Strategy: North Shore club; custom merch for junior sailing and social calendar.'),
  ('info@sayvilleyachtclub.org', '(631) 363-9581', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Sayville Yacht Club', 'Yacht & Country Club', 'Sayville', false, false, 'Contact: Club Office / Commodore | Website: sayvilleyachtclub.org | Distance/Region: South Shore | Target Service: Custom Embroidered Canvas Totes | Strategy: Historic 1901 dinghy-racing club hosting national regattas; pitch custom embroidered canvas totes and sun hats for the junior sailing program and summer social calendar.'),
  ('info@babylonyachtclub.com', '(631) 669-9671', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Babylon Yacht Club', 'Yacht & Country Club', 'West Islip', false, false, 'Contact: Clubhouse / Membership Office | Website: babylonyachtclub.com | Distance/Region: South Shore | Target Service: Custom Embroidered Canvas Totes | Strategy: Est. 1903 Great South Bay yacht club with active junior sailing and social program; propose custom embroidered gear totes and caps for junior fleet members and summer regatta swag.'),
  ('info@hamptonscommunityoutreach.org', '(631) 250-9898', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Hamptons Community Outreach', 'Charity / Non-Profit', 'Water Mill', false, false, 'Contact: Executive Director | Website: hamptonscommunityoutreach.org | Distance/Region: East End | Target Service: Custom Embroidered Canvas Totes | Strategy: Youth development & food outreach; custom organic canvas totes for donor kits and community events.'),
  ('info@olaofeasternlongisland.org', '(631) 899-3441', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'OLA of Eastern Long Island', 'Charity / Non-Profit', 'East Hampton', false, false, 'Contact: Development / Events | Website: olaofeasternlongisland.org | Distance/Region: East End | Target Service: Custom Embroidered Canvas Totes | Strategy: Advocacy organization; custom branded merch for community fundraisers and awareness events.'),
  ('events@arfhamptons.org', '(631) 537-0400', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'Animal Rescue Fund of the Hamptons (ARF)', 'Charity / Non-Profit', 'East Hampton', false, false, 'Contact: Events Director | Website: arfhamptons.org | Distance/Region: East End | Target Service: Custom Embroidered Canvas Totes | Strategy: Major animal rescue; donate party packages for galas + custom dog-mom hats and rescue totes.'),
  ('info@thegateway.org', '(631) 286-1133', 'lead', 'other', 'gemini_scrape (hh-scraped batch 2026-08; community outreach)', true, 'The Gateway (Performing Arts Center of Suffolk County)', 'Charity / Non-Profit', 'Bellport', false, false, 'Contact: Development / Events Office | Website: thegateway.org | Distance/Region: South Shore | Target Service: Gala Auction & Custom Merch | Strategy: Long-running 501(c)(3) professional theater hosting an annual gala fundraiser; pitch a donated party package for the live auction plus custom printed canvas totes as a gala gift-bag item.')
ON CONFLICT (email) DO NOTHING;

-- Tags: category-slug + type (b2b-partner|community-outreach) + batch, derived from the just-inserted rows.
INSERT INTO public.contact_tags (contact_id, tag)
SELECT c.id, t.tg
FROM public.contacts c
CROSS JOIN LATERAL (VALUES
  (trim(both '-' from lower(regexp_replace(c.business_type, '[^a-zA-Z0-9]+', '-', 'g')))),
  (CASE WHEN c.source_detail LIKE '%b2b partnership%' THEN 'b2b-partner' ELSE 'community-outreach' END),
  ('ai-scrape-2026-08')
) AS t(tg)
WHERE c.source_detail LIKE 'gemini_scrape (hh-scraped batch 2026-08%'
ON CONFLICT (contact_id, tag) DO NOTHING;

-- Verification (run manually):
-- SELECT count(*) FROM public.contacts WHERE source_detail LIKE 'gemini_scrape (hh-scraped batch 2026-08%';  -- expect 41
-- SELECT tag, count(*) FROM public.contact_tags GROUP BY tag ORDER BY 2 DESC;
